### ISSUE TITLE
User is still a required variable in settings.

### ISSUE THREAD

**Issue by cosmosquark** [SectorAlpha/AlphaGSM#1]
Ideally, we would like any use to download this software without having to do any config setup.

At the moment, user is still a required variable.

 python3 alphagsm mymcserver create minecraft
Traceback (most recent call last):
  File "alphagsm", line 5, in <module>
    sys.exit(core.main(sys.argv[0],sys.argv[1:]))
  File "/...../alphagsm/AlphaGSM/core/main.py", line 69, in main
    return runone(name,servers[0],cmd,args)
  File "/...../alphagsm/AlphaGSM/core/main.py", line 87, in runone
    server=Server(tag,args[0])
  File "/...../alphagsm/AlphaGSM/server/server.py", line 119, in __init__
    truename,self.module=_findmodule(self.data["module"])
  File "/...../alphagsm/AlphaGSM/server/server.py", line 32, in _findmodule
    module=import_module(SERVERMODULEPACKAGE+name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/...../alphagsm/AlphaGSM/gamemodules/minecraft/vanilla.py", line 10, in <module>
    import downloader
  File "/...../alphagsm/AlphaGSM/downloader/__init__.py", line 7, in <module>
    from .downloader import *
  File "/...../alphagsm/AlphaGSM/downloader/downloader.py", line 14, in <module>
    USER=settings.system.downloader['user'] # required
  File "/...../alphagsm/AlphaGSM/utils/settings/_settings.py", line 31, in __getitem__
    return self._dict[key]
KeyError: 'user'

Additionally, we still need the config file to exist.

**Comment by cosmosquark** [comment]
This was fixed in a previous commit. The default user is now the user who is currently logged in.
